Sprint 7 solution in file manager
denis-repkov/java-kanban pull request #1
Opened 2024-06-25 13:38 UTC by denis-repkov

2024-06-25 20:00 UTC, z8q requested changes

2024-06-25 20:00 UTC, z8q commented on resources/backupTasks.csv
> +id,type,name,status,description,epic
Есть ошибки на шаге Build tests – find: ‘./test’: No such file or directory
нужно поправить

2024-06-25 20:00 UTC, z8q commented on src/ru/homework/kanban/manager/Managers.java
> +        return FileBackedTaskManager.loadFromFile(new File("resources/backupTasks.csv"));
для чего создавать менеджер в строке 8
и еще раз создавать в 9-й, и возвращать последний
есть ли необходимость?

2024-06-25 20:00 UTC, z8q commented on src/ru/homework/kanban/manager/FileBackedTaskManager.java
> +            e.printStackTrace();
В методе save лучше бросить ManagerException, чем просто printStackTrace
Если сохранение не работает/происходит с ошибками, работу программы лучше завершать

2024-06-26 12:00 UTC, denis-repkov commented on resources/backupTasks.csv
> +id,type,name,status,description,epic
Добавил директорию test + сами тесты

2024-06-26 12:00 UTC, denis-repkov commented on src/ru/homework/kanban/manager/Managers.java
> +        return FileBackedTaskManager.loadFromFile(new File("resources/backupTasks.csv"));
Согласен с замечанием, убрал строку

2024-06-26 12:01 UTC, denis-repkov commented on src/ru/homework/kanban/manager/FileBackedTaskManager.java
> +            e.printStackTrace();
Исправил на выброс сообщения ManagerException

2024-06-26 18:12 UTC, z8q approved these changes

2024-06-27 07:27 UTC, merged