реализация ТЗ-8:
denis-repkov/java-kanban pull request #2
Opened 2024-08-17 20:12 UTC by denis-repkov

- добавление даты/времени начала выполнения задачи и её продолжительности
- добавлена возможность вывода задач в порядке приоритета выполнения
- обновлены unit-тесты, согласно изменениям

2024-08-19 05:55 UTC, z8q requested changes

2024-08-19 05:55 UTC, z8q commented on src/ru/homework/kanban/tasks/Task.java
> +        return Objects.requireNonNullElseGet(startTime, LocalDateTime::now);
Тут может быть такая проблема, что таски с startTime == null будут сложены в упорядоченном Set не в одном месте, а в зависимости от текущего времени

Можно попробовать доработать comparator для startTime == null

В нем есть возможность обработки  null значений, вот пример
```JAVA
private final Comparator<Task> taskComparator = Comparator.comparing(
    Task::getStartTime,
    Comparator.nullsFirst(Comparator.naturalOrder())
);
```

2024-08-19 05:55 UTC, z8q commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +                        (prioritizedTask.getStartTime().isEqual(startOfTask) ||
Возможный простой способ проверки на пересечения,
мы проверяем
- если x1 позднее y2, пересечения точно нет
- если y1 позднее x2, пересечения точно нет

В остальных случаях пересечение есть
```
private boolean isIntersected(...) {
    if (!x1.isAfter(y2) && !y1.isAfter(x2)) {
        return true;
    } else {
        return false
    }
}
```

2024-08-19 05:55 UTC, z8q commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +            if (epic.getStartTime().isAfter(subtasks.get(id).getStartTime())) {
внутри for можно сделать переменные для повторяющихся 
subtasks.get(id).getStartTime()
subtasks.get(id).getEndTime()
чтобы улучшить читаемость

2024-08-19 05:55 UTC, z8q commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +            }
Дополнительно с исключением ничего не делаем, по идее можно и не бросать

Можно попробовать упростить try/catch до такого вида.
```JAVA
               if (!checkIntersections(subtask)) {
                    int e = oldSubtask.getEpicId();
                    epics.get(e).removeSubtaskId(subtask.getId());
                    prioritizedTasks.removeIf(prioritizedTask -> prioritizedTask.equals(oldSubtask));
                    addToPrioritizedTasks(subtask);
                    subtasks.put(subtask.getId(), subtask);
                    epics.get(subtask.getEpicId()).addSubtaskId(subtask.getId());
                    updateEpicStatus(e);
                    updateEpicStatus(subtask.getEpicId());
                    changeEpicTiming(epics.get(subtask.getEpicId()));
                } else {
                    System.out.println("Найдено пересечение во времени, подзадача не изменена");
                }
```

2024-08-19 05:55 UTC, z8q commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +            }
выше по коду тоже таки блоки есть, можно упростить

2024-08-19 05:55 UTC, z8q commented on test/ru/homework/kanban/manager/FileBackedTaskManagerTest.java
> +        assertEquals(manager.getPrioritizedTasks(), loadedManager.getPrioritizedTasks(), "Списки приоритетов не одинаковы");
Можно сделать тест, который бы проверял, что происходит с порядком в prioritizedTasks

Когда создаем задачи с указанным startTime и задачи с startTime == null

2024-08-19 05:55 UTC, z8q commented on test/ru/homework/kanban/manager/InMemoryHistoryManagerTest.java
Можно еще потестить случаи, когда добавляем таску, которая пересекается по времени

2024-08-19 08:30 UTC, denis-repkov commented on src/ru/homework/kanban/tasks/Task.java
> +        return Objects.requireNonNullElseGet(startTime, LocalDateTime::now);
Добавил в компаратор обработку null-значений

2024-08-19 08:31 UTC, denis-repkov commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +                        (prioritizedTask.getStartTime().isEqual(startOfTask) ||
Упростил способ проверки на пересечения, согласно рекомендации

2024-08-19 08:31 UTC, denis-repkov commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +            if (epic.getStartTime().isAfter(subtasks.get(id).getStartTime())) {
Добавил переменные для повторяющихся значений

2024-08-19 08:33 UTC, denis-repkov commented on src/ru/homework/kanban/manager/InMemoryTaskManager.java
> +            }
Убрал блок try/catch с выбрасываемым исключением, заменил его на печать сообщения

2024-08-19 08:56 UTC, denis-repkov commented on test/ru/homework/kanban/manager/InMemoryHistoryManagerTest.java
Добавил тест для проверки добавления задачи с пересечением по времени

2024-08-19 11:16 UTC, denis-repkov commented on test/ru/homework/kanban/manager/FileBackedTaskManagerTest.java
> +        assertEquals(manager.getPrioritizedTasks(), loadedManager.getPrioritizedTasks(), "Списки приоритетов не одинаковы");
Добавил тест для проверки задачи со startTime == null в списке приоритетов

2024-08-20 05:47 UTC, z8q approved these changes

2024-08-20 05:47 UTC, z8q commented on test/ru/homework/kanban/manager/FileBackedTaskManagerTest.java
> +        assertEquals(taskId, prioritizedTasks.get(0).getId(), "Задача с пустой датой начала должна быть 1-ой в списке");
Тут все таки порядок возникает не на основе null value

в классе Task есть геттер
```JAVA
public LocalDateTime getStartTime() {
        return Objects.requireNonNullElseGet(startTime, LocalDateTime::now);
}
```
который не вернет null

Поэтому приходится для первой задачи делать LocalDateTime.now().plusHours(1), 
чтобы вторая оказалась 1-ой в списке

2024-08-20 06:40 UTC, merged