реализация ТЗ-9:
denis-repkov/java-kanban pull request #3
Opened 2024-08-21 15:38 UTC by denis-repkov

- добавлены API-методы + тесты

2024-08-22 15:17 UTC, z8q requested changes

2024-08-22 15:17 UTC, z8q commented on src/ru/homework/kanban/http/handler/EpicHttpHandler.java
> +                InputStream inputStream = httpExchange.getRequestBody();
InputStream можно посмотреть, он Closeable
можно создание переменной поместить в try с ресурсами

после выполнения кода внутри try будет автоматом вызван close() для inputStream

try(InputStream inputStream = httpExchange.getRequestBody()) {
    // ...
}

2024-08-22 16:07 UTC, denis-repkov commented on src/ru/homework/kanban/http/handler/EpicHttpHandler.java
> +                InputStream inputStream = httpExchange.getRequestBody();
Поправил: в хендлерах добавил конструкцию try-with-resources для inputStream

2024-08-23 07:02 UTC, z8q approved these changes

2024-08-23 07:51 UTC, merged